Fix triaged-jobs s3fs mapping
MAAP-Project/maap-api-nasa pull request #101
Opened 2024-02-27 20:01 UTC by bsatoriu

Add a new mapping to the triaged jobs s3 folder to allow for file path copying from the ADE `triaged-jobs` mounted directory. For more info see: https://github.com/MAAP-Project/Community/issues/656

2024-02-27 21:52 UTC, grallewellyn requested changes
Both the triaged-jobs and triaged_job folder are empty in develop and this branch when I build a test image in DIT
But if I add 
```
- name: s3fs-volume
                    mountPath: /projects/triaged-jobs
                    subPath: triaged-jobs
                    mountPropagation: HostToContainer
```
and 
```
- name: s3fs-volume
                    mountPath: /triaged-jobs
                    subPath: triaged-jobs
                    mountPropagation: Bidirectional
```
to the devfile

Then the develop branch gives results in the triaged-jobs folder, and the triaged-jobs-mapping branch also gives results in the triaged-jobs folder

I thought before we were discussing making this change by doing something like this to the devfiles: https://github.com/MAAP-Project/maap-workspaces/compare/develop...feature/triaged_job-folder

Also note that I was unable to test this because the branch name was `bug/triaged-jobs-mapping` but if I made a new branch called `triaged-jobs-mapping` I could test. Do we think this is possible to fix?

2024-02-27 22:42 UTC, bsatoriu commented
> I thought before we were discussing making this change by doing something like this to the devfiles: [MAAP-Project/maap-workspaces@develop...feature/triaged_job-folder](https://github.com/MAAP-Project/maap-workspaces/compare/develop...feature/triaged_job-folder)
> 

@grallewellyn we originally decided on `triaged-jobs` because the use of the hyphen is consistent with the other mounted folders: `my-private-bucket`, `my-public-bucket` and `shared-buckets`. What is the concern with keeping it as `triaged-jobs`? 

> Also note that I was unable to test this because the branch name was `bug/triaged-jobs-mapping` but if I made a new branch called `triaged-jobs-mapping` I could test. Do we think this is possible to fix?

I'm not sure if you are you referring to local testing or this a CI issue you're seeing, but we should probably open a separate ticket if it's unrelated to the triaged-jobs folder issue.

Once this PR is approved and merged into develop, the change will be available to test in DIT and we can verify that the presigned s3 links are generated correctly inside of the `triaged-job` directory.

2024-02-27 23:28 UTC, grallewellyn commented
Ah okay I didn't realize this PR was changing the outputs of the jobs to now contain `triaged-jobs` instead of `triaged_job` rather than changing the folder name, but that works too and sounds like it would be more consistent. The only concern is, is this retroactive for all already failed jobs?

I think we still need a PR into maap-workspaces develop to add
```
- name: s3fs-volume
                    mountPath: /projects/triaged-jobs
                    subPath: triaged-jobs
                    mountPropagation: HostToContainer
```
and
```
- name: s3fs-volume
                    mountPath: /triaged-jobs
                    subPath: triaged-jobs
                    mountPropagation: Bidirectional
```
to the devfiles 

When I test this in DIT by building a test image here: https://repo.dit.maap-project.org/root/maap-api-nasa-ci/-/pipelines then running a job that fails, the output link still contains `triaged_job` instead of `triaged-jobs`. I was under the impression we could test all changes to maap-api-nasa by building a test image there, but maybe I am incorrect?

Sorry yes I meant this was tested on the CI, I opened a new ticket here: https://github.com/MAAP-Project/Community/issues/931

2024-02-27 23:43 UTC, bsatoriu commented
> Ah okay I didn't realize this PR was changing the outputs of the jobs to now contain `triaged-jobs` instead of `triaged_job` rather than changing the folder name, but that works too and sounds like it would be more consistent. The only concern is, is this retroactive for all already failed jobs?

The job outputs still go to the `triaged_job` folder in s3. The mapped folder in the ADE is arbitrary, so it doesn't have to match the s3 path. We map the path name here: https://repo.dit.maap-project.org/root/che-sidecar-s3fs/-/blob/master/entrypoint.sh#L37

> 
> I think we still need a PR into maap-workspaces develop to add
> 
> ```
> - name: s3fs-volume
>                     mountPath: /projects/triaged-jobs
>                     subPath: triaged-jobs
>                     mountPropagation: HostToContainer
> ```
> 
> and
> 
> ```
> - name: s3fs-volume
>                     mountPath: /triaged-jobs
>                     subPath: triaged-jobs
>                     mountPropagation: Bidirectional
> ```
> 
> to the devfiles

LGTM

> 
> When I test this in DIT by building a test image here: https://repo.dit.maap-project.org/root/maap-api-nasa-ci/-/pipelines then running a job that fails, the output link still contains `triaged_job` instead of `triaged-jobs`. I was under the impression we could test all changes to maap-api-nasa by building a test image there, but maybe I am incorrect?

The output link is supposed to contain `triaged_job` (see my first comment above).

> 
> Sorry yes I meant this was tested on the CI, I opened a new ticket here: [MAAP-Project/Community#931](https://github.com/MAAP-Project/Community/issues/931)

2024-02-27 23:55 UTC, grallewellyn commented
> The output link is supposed to contain triaged_job (see my first comment above).
If the output link contains `triaged_job` and we keep the ADE folder name `triaged-jobs` to be consistent, then how do we want to fix the mapping issue for copying the jobs output?

2024-02-28 00:43 UTC, grallewellyn approved these changes

2024-02-28 00:44 UTC, grallewellyn commented
There was confusion what ticket this PR was for, I am able to see the presigned url for files in the triaged-jobs folder so approving 
<img width="1295" alt="Screenshot 2024-02-27 at 4 44 09 PM" src="https://github.com/MAAP-Project/maap-api-nasa/assets/114033465/ff51dff3-57e3-4186-b9b6-ea797dca9c3c">

2024-02-28 01:00 UTC, merged